### ISSUE TITLE
Замечания по программе Lab 0 Task 4

### ISSUE THREAD

**Issue by alexey-malov** [Romasmi/cpp_oop_practice#3]
Совет:
```
#include <utility>

enum class Operation
{
    Addition, Subtraction, Multiplication, Division
};
const std::pair<char, Operation> CHAR_TO_OPERATION[] = 
{
    { '+', Operation::Addion },
    { '-', Operation::Subtraction },
    { '*', Operation::Multiplication },
    { '/', Operation::Division },
};

bool DecodeOperation(char ch, Operation& operation)
{
    for (auto& op : CHAR_TO_OPERATION)
    {
        if (op.first == ch)
        {
            operation = op.second;
            return true;
        }
    }
    return false;
};
```

**Comment by alexey-malov** [comment]
```c++
	catch (exception e)
	{
		cout << "One or more operands aren't' valid \n";
		cout << e.what() << endl;
		return 1;
	}
```
- [ ] Исключения следует ловить [по ссылке](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#e15-catch-exceptions-from-a-hierarchy-by-reference)

**Comment by alexey-malov** [comment]
- [ ] Каждый цикл - это некоторый алгоритм. Дайте ему имя и вынесите из функции main

**Comment by Romasmi** [comment]
Fixed by commit [9117abd128480dcd64d85136304102ebcdaef2d0](https://github.com/Romasmi/cpp_oop_practice/commit/9117abd128480dcd64d85136304102ebcdaef2d0)

**Comment by alexey-malov** [comment]
- [ ] В main слишком много try/catch, что усложняет код. Достаточно, наверное, одного блока try

**Comment by alexey-malov** [comment]
- [ ] Тесты покрывают лишь часть ситуаций
- [ ] Не хватает проверки вычитания
