### ISSUE TITLE
Замечания по программе Replace

### ISSUE THREAD

**Issue by alexey-malov** [Romasmi/cpp_oop_practice#4]
```c++
string StringReplace(string line, const string search, const string replace)
{
	string newLine = "";
	size_t currentPosition = 0;
	size_t searchLength = search.length();
	size_t lineLength = line.length();
```
- [x] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению
- [x] Не нужно присваивать строке "" - она по умолчанию в с++ будет пустой

**Comment by alexey-malov** [comment]
```c++
	while (currentPosition + searchLength < lineLength)
	{
		const string subString = line.substr(currentPosition, searchLength); // <-- тут создаётся новая строка
		if (subString == search)
		{
			newLine += replace;
			currentPosition += searchLength;
		}
		else
		{
			newLine += line[currentPosition];
			++currentPosition;
		}
	}
```

- [ ] В строке есть метод find, можно использовать его

**Comment by alexey-malov** [comment]
```c++
void CopyFileByReplacing(fstream& input, fstream& output, const string search,
	const string replace)
{
```
- [ ] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

**Comment by alexey-malov** [comment]
```c++
	fstream input(argv[1], istream::in);
	fstream output(argv[2], ostream::out);
```

- [ ] Из одного потока вы всегда читаете, а в другой всегда пишете. Поэтому используйте ifstream и ofstream

**Comment by alexey-malov** [comment]
- [ ] Из main выделить функцию CopyFileByReplacing, которая принимала бы имена файлов, искомую строку и строку-заменитель и вызывала функцию CopyFileByReplacing, принимающую потоки

**Comment by alexey-malov** [comment]
- [ ] Если в качестве искомой строки задать пустую, программа зависнет. В случае, когда искомая строка пустая, должно считаться, что она ни в одну строку не входит

**Comment by alexey-malov** [comment]
```c++
	if (lineLength - currentPosition > 0)
	{
		newLine += line.substr(currentPosition, lineLength - currentPosition);
	}
```

- [ ] вместо извлечения подсторки используйте append, позволяющий добавить часть строки

**Comment by alexey-malov** [comment]
```
1>c:\teaching\ips\2018\oop\smirnov\cpp_oop_practice\lab_1\task_1\task_1.cpp(66): warning C4715: 'CopyFileByReplacing': not all control paths return a value
```

- [ ] Не хватает return

**Comment by Romasmi** [comment]
Fixed by commit https://github.com/Romasmi/cpp_oop_practice/blob/27cc9777c18b8b42ef8cb4f3cbc5ad77404f7eb8/lab_1/task_1/task_1.cpp
