### ISSUE TITLE
Замечания по программе Radix

### ISSUE THREAD

**Issue by alexey-malov** [Romasmi/cpp_oop_practice#5]
```c++
1>c:\teaching\ips\2018\oop\smirnov\cpp_oop_practice\lab_1\task_2\task_2.cpp(77): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>c:\teaching\ips\2018\oop\smirnov\cpp_oop_practice\lab_1\task_2\task_2.cpp(88): warning C4244: 'argument': conversion from 'double' to 'const unsigned int', possible loss of data
```

- [x] Для индексации контейнеров STL следует использовать size_t
- [x] Избавиться от pow

**Comment by alexey-malov** [comment]
- [ ] При переводе нуля из любой системы счисления в любую программа не выводит ничего. Воспроизвести в тестах, исправить проблему

**Comment by alexey-malov** [comment]
- [ ] При переводе FFFFFFFF из 16 в 10 программа сообщает о переполнении, хотя FFFFFFFE - не сообщает. Исправить проблему (должно переводиться нормально)

**Comment by Romasmi** [comment]
При входном числе FFFFFFFF (4294967295) программа выдаст ошибку, т.к.  numeric_limits<unsigned int>::max() = 4294967295 (Проверено выводов в output инструкцией cout << numeric_limits<unsigned int>::max() << endl;)

**Comment by alexey-malov** [comment]
```c++
	if (str.length() <= 0)
	{
		wasError = true;
		return 0;
	}
```

- [ ] Метод length() возвращает значение типа size_t, которое не может быть меньше 0. Кроме того, даже если бы он возвращал знаковый тип, то в нормально спроектированном классе строки отрицательная длина была бы невозможной

**Comment by alexey-malov** [comment]
```c++
unsigned int GetMul(const unsigned int a, const unsigned b)
{
	if (a == 0 || ((numeric_limits<unsigned int>::max() / b + 1) >  a))
```

- [ ] Если `b == 1`, программа неверно отрепортит переполнение. +1 - это костыль.

**Comment by alexey-malov** [comment]
```c++
		unsigned int currentDischargeNumber = LetterToNumber(str[i]);
```
- [ ] Разряд (числа) - digit. Discharge - электрический разряд

**Comment by alexey-malov** [comment]
```c++
	return InInterval(letter, '0', '9') ? static_cast<int>(letter - '0') : static_cast<int>(letter) - 55;
```

- [ ] 55 - магическое число. Выразите его через символ 'A' и число 19

**Comment by alexey-malov** [comment]
```c++
		unsigned int currentDischargeNumber = LetterToNumber(str[i]);
		if (currentDischargeNumber > radix)
		{
			wasError = true;
			return 0;
		}
```

- [ ] Ошибка в сравнении

**Comment by alexey-malov** [comment]
- [ ] Функции IsValidated, Convert выглядят тяжёлыми для восприятия

**Comment by alexey-malov** [comment]
- [ ] Функции, выполняющие вычисления, не должны выводить в cout ничего. Раз уж используете исключения, то и код обработки ошибок разместитье в одном месте внутри main

**Comment by Romasmi** [comment]
Fixed by commit https://github.com/Romasmi/cpp_oop_practice/commit/95c9f55c466bac6616b498d881d2029726163fd9

**Comment by alexey-malov** [comment]
```c++
bool ValidStringNumber(string number)
{
	try
	{
		int tempNumber = stoi(number);
	}
	catch (const exception& e)
	{
		return false;
	}
}
```

- [ ] Не во всех случаях функция возвращает значения.

**Comment by alexey-malov** [comment]
- [ ] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.
